### ISSUE TITLE
Creation of unique index after migration on forked table blocks transactions in first table

### ISSUE THREAD

**Issue by NGRichter** [quantumdb/quantumdb#81]
I am making a demonstration right now and I am performing a migration with load on the original schema version where at the end the transactions just dropped. So I looked at what QuantumDB was doing and it was making a unique index. 
I came to the conclusion that this will block the original table as the trigger to upsert data into the newly forked table gets blocked.

This index should either be made before migration or with the CONCURRENTLY keyword

**Comment by michaeldejong** [comment]
Good catch. Looks like there are two options (as you rightly identified):

- Make the `CREATE INDEX` query in `TableCreator.java:136` concurrent as you suggest.
- Make the indices before copying the data over between tables (instead of after copying) in `PostgresqlMigrator.java:335`.

Upside of creating the indices before copying is that it will fail the copy process quite quickly, if a (new) unique index is violated in the process. Downside is that this will be a lot slower as typically inserting data and then adding indices is quicker than the reverse. I think in this case we should favor copy speed, so adding `CONCURRENTLY` to the query. 

If you haven't done so already, I'll try to add that later today.
